// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/lib/js/src/jest.js");
var PolishedCss__Color = require("../src/PolishedCss__Color.js");

function toEqual(x, y) {
  return Jest.Expect.toEqual(y, x);
}

Jest.describe("Color", (function (param) {
        Jest.test("shade", (function (param) {
                var x = Jest.Expect.expect(PolishedCss__Color.shade({
                          NAME: "hex",
                          VAL: "ff0000"
                        }, 0.25));
                return Jest.Expect.toEqual({
                            NAME: "hex",
                            VAL: "bf0000"
                          }, x);
              }));
        Jest.test("tint", (function (param) {
                var x = Jest.Expect.expect(PolishedCss__Color.tint({
                          NAME: "hex",
                          VAL: "ff0000"
                        }, 0.25));
                return Jest.Expect.toEqual({
                            NAME: "hex",
                            VAL: "ff3f3f"
                          }, x);
              }));
        Jest.test("darken", (function (param) {
                var x = Jest.Expect.expect(PolishedCss__Color.darken({
                          NAME: "hex",
                          VAL: "ff0000"
                        }, 0.25));
                return Jest.Expect.toEqual({
                            NAME: "hex",
                            VAL: "800000"
                          }, x);
              }));
        Jest.test("lighten", (function (param) {
                var x = Jest.Expect.expect(PolishedCss__Color.lighten({
                          NAME: "hex",
                          VAL: "ff0000"
                        }, 0.25));
                return Jest.Expect.toEqual({
                            NAME: "hex",
                            VAL: "ff8080"
                          }, x);
              }));
        return Jest.test("transparentize", (function (param) {
                      var y = PolishedCss__Color.Rgba.fromString("rgba(255, 0, 0, 0.5)");
                      var x = Jest.Expect.expect(PolishedCss__Color.transparentize({
                                NAME: "hex",
                                VAL: "ff0000"
                              }, 0.5));
                      return Jest.Expect.toEqual(y, x);
                    }));
      }));

exports.toEqual = toEqual;
/*  Not a pure module */
