// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/lib/js/src/jest.js");
var PolishedCss__Color = require("../src/PolishedCss__Color.js");

function toEqual(x, y) {
  return Jest.Expect.toEqual(y, x);
}

Jest.describe("Color", (function (param) {
        Jest.test("shade", (function (param) {
                var x = Jest.Expect.expect(PolishedCss__Color.shade({
                          NAME: "hex",
                          VAL: "ff0000"
                        }, 0.25));
                return Jest.Expect.toEqual({
                            NAME: "hex",
                            VAL: "bf0000"
                          }, x);
              }));
        Jest.test("tint", (function (param) {
                var x = Jest.Expect.expect(PolishedCss__Color.tint({
                          NAME: "hex",
                          VAL: "ff0000"
                        }, 0.25));
                return Jest.Expect.toEqual({
                            NAME: "hex",
                            VAL: "ff3f3f"
                          }, x);
              }));
        Jest.test("darken", (function (param) {
                var x = Jest.Expect.expect(PolishedCss__Color.darken({
                          NAME: "hex",
                          VAL: "ff0000"
                        }, 0.25));
                return Jest.Expect.toEqual({
                            NAME: "hex",
                            VAL: "800000"
                          }, x);
              }));
        Jest.test("lighten", (function (param) {
                var x = Jest.Expect.expect(PolishedCss__Color.lighten({
                          NAME: "hex",
                          VAL: "ff0000"
                        }, 0.25));
                return Jest.Expect.toEqual({
                            NAME: "hex",
                            VAL: "ff8080"
                          }, x);
              }));
        Jest.test("transparentize", (function (param) {
                var y = PolishedCss__Color.Rgba.fromString("rgba(255, 0, 0, 0.5)");
                var x = Jest.Expect.expect(PolishedCss__Color.transparentize({
                          NAME: "hex",
                          VAL: "ff0000"
                        }, 0.5));
                return Jest.Expect.toEqual(y, x);
              }));
        Jest.test("getContrast", (function (param) {
                var x = Jest.Expect.expect(PolishedCss__Color.getContrast({
                          NAME: "hex",
                          VAL: "ff0000"
                        }, {
                          NAME: "hex",
                          VAL: "0000ff"
                        }));
                return Jest.Expect.toEqual(2.16, x);
              }));
        Jest.test("getLuminance", (function (param) {
                var x = Jest.Expect.expect(PolishedCss__Color.getLuminance({
                          NAME: "hex",
                          VAL: "ff0000"
                        }));
                return Jest.Expect.toEqual(0.213, x);
              }));
        Jest.test("grayscale", (function (param) {
                var x = Jest.Expect.expect(PolishedCss__Color.grayscale({
                          NAME: "hex",
                          VAL: "ff0000"
                        }));
                return Jest.Expect.toEqual({
                            NAME: "hex",
                            VAL: "808080"
                          }, x);
              }));
        Jest.test("desaturate", (function (param) {
                var x = Jest.Expect.expect(PolishedCss__Color.desaturate({
                          NAME: "hex",
                          VAL: "ff0000"
                        }, 0.3));
                return Jest.Expect.toEqual({
                            NAME: "hex",
                            VAL: "d92626"
                          }, x);
              }));
        Jest.test("complement", (function (param) {
                var x = Jest.Expect.expect(PolishedCss__Color.complement({
                          NAME: "hex",
                          VAL: "ff0000"
                        }));
                return Jest.Expect.toEqual({
                            NAME: "hex",
                            VAL: "0ff"
                          }, x);
              }));
        return Jest.test("adjustHue", (function (param) {
                      var x = Jest.Expect.expect(PolishedCss__Color.adjustHue({
                                NAME: "hex",
                                VAL: "ff0000"
                              }, 0.3));
                      return Jest.Expect.toEqual({
                                  NAME: "hex",
                                  VAL: "ff0100"
                                }, x);
                    }));
      }));

exports.toEqual = toEqual;
/*  Not a pure module */
