// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Polished = require("polished");

function between(minScreen, maxScreen, fromSize, toSize, param) {
  return Polished.between(fromSize.VAL, toSize.VAL, minScreen, maxScreen);
}

exports.between = between;
/* polished Not a pure module */
