// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Polished = require("polished");

function math(prim, prim$1) {
  return Polished.math(prim, prim$1);
}

exports.math = math;
/* polished Not a pure module */
